import { describe, expect, it } from "vitest";
import type { ActionPackage } from "../../src/core/types.js";

describe("MPAS Core types", () => {
  it("allows a fully typed sample Action Package", () => {
    const actionPackage: ActionPackage = {
      version: "1",
      type: "ActionPackage",
      executionPayload: {
        name: "create_issue_mirror",
        arguments: {
          owner: "oma3dao",
          repo: "app-registry",
          title: "Add MPAS fixture",
          body: "Generated by a type-checking sample.",
        },
      },
      actionEnvelope: {
        version: "1",
        type: "ActionEnvelope",
        proposer: {
          did: "did:web:agents.example:proposer",
        },
        target: {
          applicationDid: "did:web:github-mirror.example",
          resource: "repo:oma3dao/app-registry",
        },
        executionProfile: {
          id: "did:web:profiles.oma3.org:mcp",
          format: "mcp.toolsCall",
        },
        executionPayloadHash: {
          alg: "sha-256",
          value: "base64url-encoded-digest",
        },
        actionId: {
          value: "urn:uuid:3f82f6e1-135e-44c5-90a9-58f760f6d9f1",
        },
        createdAt: "2026-05-27T18:00:00.000Z",
        expiresAt: "2026-05-27T19:00:00.000Z",
      },
      approvalBundle: {
        version: "1",
        type: "ApprovalBundle",
        actionEnvelopeHash: {
          alg: "sha-256",
          value: "base64url-encoded-envelope-digest",
        },
        approvals: [
          {
            version: "1",
            type: "Approval",
            actionEnvelopeHash: {
              alg: "sha-256",
              value: "base64url-encoded-envelope-digest",
            },
            decision: "propose",
            signature: {
              format: "jws",
              value: "eyJhbGciOiJFZERTQSJ9.eyJ0eXBlIjoiQXBwcm92YWxQYXlsb2FkIn0.signature",
            },
            createdAt: "2026-05-27T18:10:00.000Z",
          },
        ],
        createdAt: "2026-05-27T18:20:00.000Z",
      },
      createdAt: "2026-05-27T18:25:00.000Z",
    };

    expect(actionPackage.type).toBe("ActionPackage");
  });
});
